* What’s in it for me? Prepare your mind for success.
https://www.blinkist.com/en/nc/reader/the-inner-game-of-tennis-en
To excel at their game, tennis players need to win an internal battle, and it’s a coach’s job to show them how.
Performance comes from quieting your conscious mind and letting go of judgments.
Trust your unconscious mind to do what it does best.
Focus your conscious mind through methodical practice.
The best way to learn is through experience and finding what works for you.
Take the Inner Game to the sports field and beyond.
Final summary
  
* What’s in it for me? Prepare your mind for success.
Whether it’s a tennis tournament or a negotiation, what does it take to win? Most people would answer that it all comes down to willpower, a great strategy and lots of sound advice from one’s coach or consultant.

Most of us would likely fire an adviser who tells us to just trust our instincts and let things happen. But as you’ll learn from these blinks, it’s this very advice that will prepare your mind for success.

Listening to your instincts above all else is the ticket to winning your inner game – that is, to overcome your self-doubt and anxiety while muting all the inner chatter that keeps you from performing at your best. It’s only when you’re winning this inner game that you can also excel in the outer game, and challenge yourself to achieve your goals.


* To excel at their game, tennis players need to win an internal battle, and it’s a coach’s job to show them how.

Lots of people have seen world-class tennis stars battling it out on the court. But there’s another struggle facing tennis players that’s not so visible: they’re also playing an inner game within themselves.

This match is between the conscious mind of the player, what can be called Self 1, and her unconscious mind, or Self 2. Just consider the tremendous effort required of players to overcome self-doubt, calm down before a match and stay positive.

Beyond that, for many players, the conscious mind judges and instructs the unconscious. That’s why you may have seen tennis players talking to themselves on the court, exclaiming things like “you klutz!”

Such situations are a prime example of the interaction between the two selves, and the ways they interact in this inner game determine how successful a player will be in the outer game. This is essential information for tennis coaches, as it’s their job to help players balance both selves.

To do so, a coach will often tell players what to do and what to avoid. The problem here is that, in many cases, the more you consciously focus on what you’re told, the less successful you are. At times like these, Self 1 is attempting to control Self 2 – and the results are rarely desirable.

A good example is how Self 1 might say stuff like “stop being so nervous!” But think about it: Would such a command actually do much to calm your nerves?

Probably not, and that’s why coaches need to teach players how to let each self do its thing, without interference from the other. By mastering this technique, a player can excel at her sport, responding to every moment practically automatically as if having an “out-of-mind” experience.

But how can both selves interact in this way? And how can you, as a coach or player, help them do so? You’ll learn the answers to these questions and more in the next blinks.

* Performance comes from quieting your conscious mind and letting go of judgments.
pivotal
stalking his prey 
fluidity 
unleash the power 
indulges self one 
rewinding a recorded 
With that being said 

Imagine you’re in the heat of a pivotal game in a big tournament. No matter what strokes you try, your opponent continues to maintain the upper hand. What should you do?

Well, if you’re like most people, you’ll remind yourself how to improve your form, say, by tightening the grip on your racket. But doing so won’t help you.

To truly play at your best, you need to quiet your conscious mind by letting go of judgment. While your conscious self is constantly thinking and judging, as any experienced player knows, peak performance only comes when thinking stops and action takes over.

So, instead of relying on your conscious mind, let Self 2 handle it. By fully immersing yourself in the match, you’ll become like a predator stalking his prey. You’ll be entirely guided by instinct and much better equipped to succeed.

This makes perfect sense, since the defining aspects of top performance, like timing and fluidity, are the specialty of Self 2. But to unleash this power, you first need to quiet your conscious mind.

Doing so is a complex process and the first step is to release all judgments. Judgment is a form of thinking that indulges Self 1 rather than constraining it. More importantly, if a judgment is negative, such as if you believe you’re clumsy, it could cause materially negative results. It could, in this example, make you self-conscious and awkward on the court.

A better strategy is to visualize yourself on the court as if you’re watching and rewinding a recorded match. This will let you focus on the movements of the ball and the racket, while enabling your Self 2 to play around with different swings. This process will help your unconscious mind improve without any coach or Self 1 telling it that it’s right or wrong.

That being said, keeping the judgments of your Self 1 at bay won’t be enough to give your Self 2 free reign. Next up, you’ll learn how to boost the unconscious mind.


* Trust your unconscious mind to do what it does best.
a recipe for disaster 
incredible 
As such = therefore 
let thing happen instead of make them happen 
chances are that s + v :: it's very likely that s + v 
overflex 
limber enough 

Anyone who has ever led a team knows that micromanaging is a recipe for disaster. A better approach is to make your goal clear, encourage your team to succeed, give them the support they need and trust that they’ll do well.

As it turns out, the same is true of Self 1 trying to micromanage Self 2. Behind Self 2 is the body, which works perfectly fine without any conscious management; in other words, you don’t have to control every little thing your body does.

For instance, while you’re focused on reading these blinks, your body, part of Self 2, is doing an incredible job of functioning. It’s breathing, keeping you sitting up straight and digesting your last meal.

So, Self 2 is very capable. It can do a great job at all kinds of tasks, even complex ones like riding a bike, singing or playing tennis.

As such, it doesn’t need orders from the conscious mind to get its job done and will actually do much better on its own. The key is to respect and trust your Self 2 while letting things happen instead of making them happen.

In fact, it’s not only unnecessary for your Self 1 to instruct your Self 2 in situations like this, it can actually be counterproductive. Just remember, when you really want something to happen, the pressure of desiring it might prevent it from happening or working out correctly.

Imagine your serve is a bit weak and you consciously tighten up the muscles in your serving arm while swinging your racket. With so much intentional focus, chances are that you’ll overflex your muscles, preventing them from being limber enough to perform well.


* Focus your conscious mind through methodical practice.
down the line
focus on the here and now 
wandering 
pay close attention 
let go of any thoughts
here lies an xx 
What’s your primary focus right now? The blinks you’re reading or how you’ll apply them down the line?

Well, for many people, it’s too easy to drift away into the future. Instead, don’t try to fight your mind. Guide it. This is especially important because your Self 1 doesn’t like to sit back – it’ll keep butting into situations until you give it a job to do. So, to keep it in line, focus it on the here and now.

Forget what might be or how things were. In tennis, your goal is to focus on where the ball is right now, not on where it might be or how you’ll respond to it.

Just watch the ball and focus in on its movement; by keeping your mind there you’ll prevent it from wandering.

In fact, it’s easy to practice focusing your mind, but not by forcing it to stare hard at something. A better way is to relax and guide your interest toward the object of your focus.

During a tennis match, this can be accomplished by paying close attention to when the ball bounces and when it hits the racket. If you say each word out loud as the actions occur, your mind won’t be able to apply excessive pressure or worry.

However, such relaxed focus can only be achieved if you are self-confident, nonjudgmental and trust yourself. So, keep in mind that focused concentration will improve your game, but it needs to be learned through practice.

Therefore, to properly focus on the here and now, practice awareness of your body, like by feeling where your racket is in your hand. And to accomplish this, you need to let go of any thoughts concerning the next actions you’ll take.

Herein lies an entirely new way of learning, which you’ll learn more about in the next blink.

  
* The best way to learn is through experience and finding what works for you.
with relative ease 
differentiate right and wrong 
the key to excellence 
keep xx very firm 
intellectualizing 
is referred to 
take the reins : control
reins 

Infants learn new skills easily and intuitively, and can even pick up foreign languages with relative ease. But as people age, something happens that gets in the way of this basic learning.

We begin to differentiate between “right” and “wrong,” and, in the process, become afraid of making mistakes. But in reality, there’s no such thing as a right or wrong way to do something. Rather, each person has to learn the method that works best for her, personally.

Just take the author, who noticed that everyone in the younger generation of tennis stars was serving in what was, in his opinion, the “wrong” way. But this technique was working for them.

It just goes to show that the key to excellence does not lie in what other people have to teach you. Instead, it’s all about finding what works best for you – this is natural learning.

Say your tennis coach instructs you to keep your wrist very firm on your backhand. If you closely follow his advice, your wrist might become too tense. So, instead of memorizing such rules, you should seek out the playing style that suits you the best.

But how?

By avoiding intellectualizing your experience. This is a fundamental step that relates to the learning power of children, who learn easily by simply observing and trying. Kids have no fear or doubt, and to learn as well as they do, you just need to trust your Self 2 without any interference from your conscious mind.

Take dancing as an example. You could sign up for dancing lessons that detail step-by-step instructions. But by doing so, your conscious mind would take the reins. Or, you could go out dancing, watch other dancers and then try it out for yourself, all while trusting that your unconscious mind has you covered.

This powerful approach is referred to by psychologists as implicit learning and it is a key factor in reaching your peak performance.

  
* Take the Inner Game to the sports field and beyond.
So, the Inner Game has clear applications in tennis, but how can you apply this knowledge to your life in general?

Well, first consider the implications the Inner Game has for sports in general: by letting go of the need to control everything, matches can become more playful and athletes can focus more intently on the present moment.

Since people often play sports to satisfy their egoistic drives, and since achievements count for a lot in our society, playing even the simplest game often becomes a way to measure and prove your value.

Naturally, such pressure produces fear, anxiety and anger. By contrast, playing the Inner Game will allow you to let go of judgment, follow your unconscious and truly enjoy what you’re doing.

But that’s not to say that competition is bad; it’s perfectly fine to play to win and stay determined. However, competition that’s actually to your benefit is about doing your best, clearing hurdles and immersing yourself in the sport, rather than trying to do better than someone else and hoping for him to mess up.

Just consider competitive surfers. If they were only in it for the joy of the sport, they’d paddle for every wave. But instead, they take the most challenging ones, which help them develop their skills. Remember: sports are not wars. Instead of fighting the other team, you should focus on clearing your own obstacles.

These are some useful ways the inner game can help recenter your sports mindset – but it doesn’t have to stop there. In fact, this wisdom is universally applicable.

Most activities involve an inner and an outer game, and to do well, you have to develop the former.

After all, your conscious self causes you stress, through judgments, for example. As a result, the inner game is about minimizing your dependence on the approval and guidance of others, and enabling your unconscious self to guide you.

Just imagine you’re in a business negotiation. You’ll have a much stronger bargaining position if you remain focused on the moment. Simply trust your skills in the present and accept what you can’t control.

* Final summary
The key message in this book:

On the tennis court just as in life in general, your conscious mind battles constantly with your unconscious. By elevating the latter and bringing both into harmony, you can unleash your true potential and excel at everything you do, from sporting arenas to the business world.

Actionable advice:

Play the role of a pro.

The next time you want to improve your game, just pretend you’re a professional. Doing so isn’t just an exercise in positive thinking, and isn’t merely a matter of telling yourself that you’re as good as a pro. Rather, it’s about consciously playing the role of a pro to become aware of your true abilities and develop a new attitude without putting too much pressure on yourself.

Got feedback?

We’d sure love to hear what you think about our content! Just drop an email to remember@blinkist.com with the title of this book as the subject line and share your thoughts!

Suggested further reading: String Theory by David Foster Wallace

String Theory (2016) is a collection of essays about tennis by David Foster Wallace. The best players in the world sacrifice their lives so that they can entertain us, but their sacrifice elevates them to a level of greatness that the rest of us lowly mortals will never achieve.
