
* Enough complaining, no more excuses: You are responsible for the course of your life.
Are you ready to ditch your unfulfilling daily routine and start living your dream life? Then let’s get started!

The first thing you need to understand on your journey to personal and professional success is that you are the director of your own life.

When we fail, we often look for an excuse, blaming the failure on things that happen to us. But how these events affect us in the long run depends on how we respond to them.

Imagine one circumstance where you receive $400. You could buy something nice for yourself, or invest the money in a mutual fund.

If you opt for the former, you have no money left. If you choose the latter, you have made an investment on which you can later build and earn even more money – a much wiser decision.

So if you want to start seeing improvements in your life, you need to change your responses.

It’s far too easy to just complain about your circumstances. But if you pay more attention to how you’re living and the choices you’re making, you’ll soon see whether you’re on the right path to success.

For instance, you’re either fit or out of shape. Ask yourself, what are you doing – or not doing – to make your body this way?

If your goal is to lose weight, you’ll need to be aware of your daily calorie intake and your level of activity. Be honest with yourself: Do you eat well? Should you cut out chocolate or junk food?

No one says that change is easy. It requires discipline, persistence and some experimentation. In the next blink, you’ll find out how to get a good start on changing your life.

The Success Principles



* Finding your purpose in life will help you better define what success means to you.

What if you’re not sure what personal success would look like for you? Relax – you’re not alone.

Slow down and take some time to contemplate. One of the first steps toward personal success is to examine your reason for being: why are you here on earth? The life purpose exercise can help you discover this.

To find your purpose, identify two of your strongest personality traits; describe the way you interact with others; and then imagine your ideal world. Once you have done this, combine these into a statement of life purpose.

You might come up with: “My purpose is to use my honesty and passion to inspire others to move forward in their chosen profession, to help contribute to a world where people have fulfilling careers.”

The next step is to create a vision – a mental picture of what your perfect future looks like. What would your perfect job be? How much free time would you have? What sort of friends?

American president John F. Kennedy, who envisioned putting a man on the moon, and civil rights leader Martin Luther King, who imagined a free and equal America for all people, were two influential visionaries. They succeeded in making seemingly unattainable ideas a reality – so why shouldn’t you do the same?

Once you have your vision in mind, break it down into smaller goals that are ambitious, specific and tangible. What do you want to achieve, and how much time will you give yourself to achieve it?

For example, being nicer to your employees may be well-meaning, but it’s not a specific, measurable goal. A clearer goal would be, “I will acknowledge six employees for their help with the latest project by the end of this week.” As you can measure your progress, you’ll know when you have achieved your goal.

Defining a goal for every part of your vision will narrow the gap between your current reality and ultimate success.


* When you visualize your dream, you should be able to see it, smell it and feel it, as if it was real.

How do you push beyond your comfort zone toward achieving your vision? Two practices – affirmation and visualization – can help you.

Affirmation starts when you state your goal as if it has already been realized, in a complete sentence. The most effective affirmations are in the first person, are positive and to the point.

For example, “I love driving down the highway in my new yellow Lamborghini” is far more effective and precise than saying, “I want a new car.” You should specify exactly what your goal will look like once you have reached it.

It is also important to add to your affirmation sentence how you will feel when you have reached your goal. Researchers have found that ideas stick in our memory better when a thought is coupled with a strong emotion.

Thus, “I feel ecstatic when I’m driving down the highway in my new yellow Lamborghini” is a great affirmation!

Once you’ve crafted your affirmations, connect each with a vivid image of your affirmation, called a visualization.

To do this, close your eyes and imagine your affirmation in as much detail as you can. If your affirmation is, “I enjoy relaxing in the sunroom of my villa in Madrid,” visualize the colors of your house, the furniture in the sunroom, and so on.

Add sounds, smells and tastes to your mental picture. What does it physically feel like to sit on the couch in your sunroom? Can you hear the sounds of the busy street, or birds singing?

The more you fill your visualisation with emotions and sensory details, the more intensely you’ll feel it, giving you more power and momentum to reach your goal.


* To succeed, be persistent, never give in to “no” and don’t forget to practice, practice, practice.

Now that you’re well on your way to achieving ultimate success, you’ll need to prepare yourself for potential obstacles and, if you depend on others, possible rejection.

Rejection is just a speedbump on the road to success. If someone says “no,” just keep trying until someone says “yes,” while keeping in mind your next step.

Kentucky Fried Chicken founder Harland Sanders was no stranger to rejection. In fact, he heard “no” more than 300 times when proposing his business idea before someone said “yes.” If he’d quit at the first rejection, there wouldn’t be more than 11,000 KFC restaurants around the world!

Best-selling author Stephen King also nearly chucked out the manuscript for his book Carrie after receiving many early rejections. But because he refused to give up, Carrie ended up selling more than 4 million copies, and was made into a film.

On your road toward your dream life, you need to excel at what you do. An important principle to focus on is to become an over-achiever. Don’t be afraid to keep trying, and work your way toward your goal one step at a time.

Take author Debbie Macomber. It took her five years of hard work before she sold her first book. She wrote for two and a half years while raising her children. To add to the pressure, her husband wanted her to give up her dream and go back to work.

However, Macomber knew she could do it and spent a further two and a half years pursuing her dream, despite being tight on cash, never taking a vacation and losing a lot of sleep. In the end, it was worth it: she’s published over 100 books and many have become best sellers.

Now that you know perseverance is the key to success, how do you allow success to happen?


* Clear your slate of unfinished business or projects: do it, delegate it, delay it or dump it.
Now that we’ve explored the fundamentals of success, let’s focus on some work you need to finish before you can really achieve your dreams.

First, you need to address unfinished business. Do you have any projects you’ve abandoned or left half-done? Do you need to clean your closet,or finish last year’s taxes? These small things can take valuable energy from achieving your larger goals.

View it this way: it’s better to have five completed projects than 15 half-completed projects.

One useful method is to schedule a completion weekend, where you take time to clear your slate of all unfinished business. Be clear and decisive: either do it, delegate it, delay it or dump it.

Although choosing to delay a project doesn’t sound productive, it differs from procrastination in that you are consciously deciding to relegate the item.

This “cleaning up” is not only applicable to tangible stuff in your life, but also to your relationships.

How much energy are you wasting, holding a grudge against a colleague who sold your work as his? How about that friend who is never around when you need her? To move forward, you need to forgive. Forgiving doesn’t mean doing someone else a favor, it means that you have let go and released tension for your own benefit.

People who have found the strength to fully forgive can experience remarkable results. In some instances, they no longer suffer from ailments such as chronic migraines, constipation or other diseases. One man even dropped six pounds within two days without changing his diet.

Picture how fantastic you would feel if you were suddenly at peace with others!

One effective technique you can use to help you forgive someone is to write a “total truth letter” to vent your anger. Write down things that have angered you, and you’ll notice that acknowledging your pain and grudges is the first step toward forgiveness.

* We are our worst enemies when it comes to believing in ourselves. Think positively!

Once you’ve taken care of unfinished business, you’ll hopefully feel like you’re already making significant progress toward your goals. Now, let’s make sure that your thoughts are in order, too.

Face it: you’re often your own biggest enemy. Most of us harbor negative thoughts about ourselves, so-called limiting beliefs, where we fixate on the things we think we can’t do. This mentality can be very damaging, as this one example shows.

A railroad worker got trapped in a refrigerated freight wagon while carrying out some repairs. Panicked, he couldn’t stop thinking about the possibility of his freezing to death, and decided to write a last message to his family.

The next morning he was found dead in the wagon. And although he showed physical signs of having frozen to death, the wagon's cooling system was actually out of order, and the temperature inside the wagon was a temperate 13°C. The man had essentially died through his own negative thinking.

To succeed, you need to stem, if not eliminate completely, your negative thoughts.

Yet if you look deep enough, self-love is often found underneath self-criticism. You might think, “I’m fat and lazy,” but if you examine this thought, what you’re really saying is, “I’m scared.”

You’re scared that you might get sick by being overweight, and in your self-criticism, you’re asking yourself to take better care of your body. You’re really saying inside: “I care about myself. I want to be healthy and strong and I deserve to feel great about my body!” This is an expression of self-love.

By transitioning from judgment to admitting fear, to a request for action and then acknowledging love, you’ll start changing your limiting beliefs into thoughts that are positive and beneficial.

So stop judging yourself and start talking to yourself like you know your real value!


* Building a support team chock-full of successful people can help you reach your goals.

Having personal resolve is crucial on your path to success, but you can’t walk that path on your own. Highly successful people always have others to inspire or mentor them along the way.

One thing you can do is to create a support group. You can do this by gathering a so-called mastermind group, a supportive circle of people with whom you can share ideas and challenges.

Consider identifying six people with whom you are close, and hold scheduled conferences or Skype calls where each person takes 15 minutes to pose questions. For you to get the most value from these sessions, each group member should excel at a skill you wish to learn, or have achieved a goal you covet.

For example, if you’re a small business owner, it might be advantageous to include one or two successful entrepreneurs from your industry in your group. Other professionals such as consultants, lawyers or investment bankers can also be of great help.

Another powerful way you can find support is to identify a mentor.

Even though it’s tempting to ask advice from friends or coworkers, it’s far more useful to ask people who’ve already achieved what you want to achieve.

You needn’t be shy about approaching successful people, as most will be eager to share their recipe for success with you.

For example, when motivational speaker Les Brown started his career, only Dr. Norman Vincent Peale, an acclaimed motivational guru, had faith in him. When Brown approached Peale, the latter was honored to share his experiences and ensured that Brown was well-equipped to become a successful coach and speaker.

You can get the ball rolling by writing an email to someone you think would make a suitable mentor, and ask if they could spare 15 minutes per month for you to share ideas and ask questions.

* Support others, and they will support you in return. Create meaningful, honest relationships!
To get the most benefit out of your support network, you must first lay a solid foundation of honesty and appreciation to build meaningful relationships.

Telling the truth can be scary. But we must tell the truth if we are to create and foster our connections with others.

Consider the story of Jack Canfield and Larry Prince and their non-profit, Foundation for Self-Esteem.

The two men submitted a proposal to design a training program for job hunters for the Los Angeles County Office for Education. However, when they realized the restrictions of the program, they decided to inform the county officers that they couldn’t comply with the regulations, thus risking losing the competition and the $730,000 grant.

But because of their honesty, they actually ended up winning the competition!

In addition to honesty, appreciation of others is often undervalued in relationships. In a study of some 200 companies, employees rated appreciation as the number-one motivator of a list of ten motivational themes; managers and supervisors, however, ranked appreciation in eighth place.

It’s clear that we want to be more appreciated at work; so be sure you do your bit by showing appreciation for others.

How exactly do you do this? It depends on the type of person you are, whether auditory, visual or tactile. The best way to appreciate others is to discover what makes them tick and combine different ways to express appreciation.

For instance, you could invite someone for dinner, give them an encouraging pat on the back, praise them over the phone or write them a thank-you card.

But crucially, be as authentic as possible. You shouldn’t hide the truth when it needs to be told. But also remember to honor and thank the people who support you.

* Being a “wealthy” person means so much more than just having a lot of cash in the bank.

Do you agree that “money is the root of all evil?”

If so, you need to redefine what wealth means to you. Most of us think that wealth is only about money, our assets or possessions. However, it’s much more than that: wealth also contains intellectual, human and civic facets.

In terms of financial assets, you may ask: what goals do I have for my property, and what stocks and bonds would I like to own?

Aside from tangible assets, try to also see how your relationships, health, morals and habits connect with how you create wealth. Also consider your education, your reputation and your skills.

Bearing these factors in mind, you can start making your wealth work to your advantage. Many financially successful people consider their human and intellectual assets to be more valuable than their financial assets, as health, happiness and relationships form a foundation for lasting financial success.

Another factor that will add considerably to your personal well-being is to offer your time to a worthy cause. Helping others has a remarkable effect on keeping us content and satisfied in our lives.

Studies on volunteerism have shown that people who help others enjoy longer and healthier lives. Also, those of us who start volunteering and helping others at a young age are more likely to benefit from a successful career later on.

Consider which causes are closest to your heart. For example, if you love to read, you could volunteer to read to the blind. You could even start a business that makes books for blind people.

To get the most out of what life can offer, you need to become “wealthy,” which means so much more than just having financial assets.

  
* Final summary
The key message in this book:

You can achieve your greatest ambitions, but it takes some know-how. Following and practicing the principles of success will equip you to reach your personal and professional goals and live your dream life.

Actionable advice:

Cross off a nagging task on your to-do list, today.

It may be as simple as filing some papers or getting your car’s oil checked, but completing a neglected task, even if just one per day, will make a huge difference toward achieving your more ambitious goals.

Ask someone you admire for 15 minutes of their time.

Find someone who has achieved a dream similar to your own and ask for 15 minutes of their time per month to advise and mentor you. The worst they can say is “no,” and in the best case, you might find a person who will be an invaluable resource in helping you live the life you want.

Suggested further reading: The Seven Habits of Highly Effective People by Stephen Covey

The Seven Habits of Highly Effective People introduces the habits which single out people who deal effectively with the world around them. The author believes that people who lead successful and fulfilling lives do not pursue a state of individual independence as their ultimate goal, but instead align themselves internally with universal principles, such as honesty and integrity.

